### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by defel** [lewster32/phaser-plugin-isometric#16]
Hi, 

phaser-plugin-isometric is not found on npmjs: https://www.npmjs.org/package/phaser-plugin-isometric

Is it possible to publish this package to npm?

```
npm publish
```

**Comment by drhayes** [comment]
:+1: for this one, as well.

**Comment by Tronix117** [comment]
If it could be added to npm as well as to bower, it would be awesome.

**Comment by nicoell** [comment]
I second this :)

**Comment by LunarDevelopment** [comment]
Not sure if you guys use bower much but the following: 
```sh
bower install --save phaser-plugin-isometric
```
works fine, and if you're using gulp / inject.js then it'll write the dependency to your index.html etc too.

**Comment by nemoDreamer** [comment]
Thanks for the bower + gulp, @LunarDevelopment . I've tended to stay away from bower, as I didn't like pulling in the entire source + build, but gulp solves that by cleaning up later.

**Comment by lewster32** [comment]
The plug-in has been published to npm (not by me; I don't use npm for this kinda stuff) here however it's probably not up-to-date with master: https://www.npmjs.com/package/phaser-plugin-isometric

**Comment by nemoDreamer** [comment]
Thanks for letting us know, @lewster32 ! @LunarDevelopment is probably right in using bower for front-end dependencies, as it seems this npm package supplies its own thin adapter layer, and as you said, would be an out-of-date fork...

**Comment by LunarDevelopment** [comment]
Super late reply, to use NPM run the following (untested..) 
```
npm install github:lewster32/phaser-plugin-isometric --save 
```

**Comment by relhtml** [comment]
@LunarDevelopment Just tested this and it installed fine. I'm using webpack and importing the isometric plugin via CommonJS. So far so good!
