### ISSUE TITLE
Example Game

### ISSUE THREAD

**Issue by LunarDevelopment** [lewster32/phaser-plugin-isometric#19]
Hello! 

Love the project, bravo! 

I was wondering if there are any example games / boilerplate for seeing this plugin in action / something to kickstart my own game prototype? 

I'm new to phaser but I've been ruined by yeoman, bower and npm for how easy it is in my job to start a new angularJS application.

Thanks, 

Lewis

**Comment by mfpierre** [comment]
Hi,

Did you check out the examples on the website ? http://rotates.org/phaser/iso/examples/

They will get you started :+1:

**Comment by LunarDevelopment** [comment]
Good call, thanks for reminding me.

I did check those out, I was just fishing for something like what you have on the website's home screen to get a big step closer to prototyping a tactics ogre / final fantasy tactics advance -esque game I've had on my to do list for a long time.. 

Would this library fit that kind or role or have I missed something when I've read through some of the docs. 

Lewis

**Comment by lewster32** [comment]
The examples demonstrate most of the features of the plug-in - there're also some tutorials such as the following:

* https://developer.tizen.org/documentation/articles/creating-isometric-world-phaser.js-using-isometric-plugin
* https://developer.tizen.org/documentation/articles/using-easystar.js-implement-pathfinding-tizen-game-projects

Finally, the source of the homepage example is unminified and reasonably well commented, though the implementation is pretty specific. You can view it here: http://www.rotates.org/phaser/iso/test.js

I'd suggest you brush up on other more generic Phaser tutorials (of which there are way too many to list) if you're not familiar with it, as the plug-in closely follows the way native Phaser features work - the physics being just a modified 3D version of the standard built-in 2D Arcade physics system.

**Comment by LunarDevelopment** [comment]
That was fantastically useful, thank you very much! 

I've got a basic version of a 3d tile map working, its just not registering the cursor location properly. 

But I think its coming from having to change the syntax of the cursor demo so drastically, I'm using generator-phaser and it separates everything into separate files and uses this. syntax.
