### ISSUE TITLE
Uncaught TypeError: Cannot read property '4' of undefined 

### ISSUE THREAD

**Issue by tiaod** [lewster32/phaser-plugin-isometric#20]
Hi, I am a beginner of phaser. I had follow [this Tutorial](https://developer.tizen.org/documentation/articles/creating-isometric-world-phaser.js-using-isometric-plugin) and I just download the code, it work normally. But if I update the `phaser-plugin-isometric.min.js` to lastest version(from v0.9.1 to v0.9.2), it throw out an error:

>Uncaught TypeError: Cannot read property '4' of undefined 

Could any one tell me what's going on here? thx :)

**Comment by mfpierre** [comment]
There is an issue with the minified file, try this one instead https://github.com/lewster32/phaser-plugin-isometric/blob/master/dist/phaser-plugin-isometric.js

I've made a PR to fix it :)

**Comment by lewster32** [comment]
Thanks for that :)
