### ISSUE TITLE
How to center map?

### ISSUE THREAD

**Issue by matiux** [lewster32/phaser-plugin-isometric#22]
I drew a tile map with a polygon tiles (ratio 2:1).
I have used game.iso.anchor.setTo(0.5, 0); to set X axes to the center of my viewport but I would like also center the Y axes. 
For center of Y axes I not mean the top corner of the map but the center of the map.
If I use game.iso.anchor.setTo(0.5, 0.5); I obtain that the top corner of the map is placed in the vertical center of the viewport.

How can I solve?

**Comment by lewster32** [comment]
I tend to use values of 0.5, 0.2 for my game.iso.anchor to provide a centered view (as evidenced in examples such as [this one](http://www.rotates.org/phaser/iso/examples/character.htm), but your results may vary. It's hard to say without seeing what you're trying to achieve. Any chance you could send me a jsfiddle, codepen or similar to demonstrate your issue?

**Comment by lewster32** [comment]
Assuming this is solved. Will re-open if an example is given of the issue.
