### ISSUE TITLE
Plugin has unexpected behaviour when Phaser is not wrapped in global.

### ISSUE THREAD

**Issue by 0nix** [lewster32/phaser-plugin-isometric#23]
The plugin has unexpected behaviour when Phaser, the plugin itself, and all other elements are wrapped in a container object. The most apparent of these is modifying isoZ in an isoGroup in `update()`. When the logic is wrapped in an object (i.e. `var env = {}; env.game = new Phaser.Game(...) )`, and the pointer interaction code is run, it acts as if a tweening motion has gone out of control.

**Comment by lewster32** [comment]
Hi 0nix, would you be able to post a link to an example of this happening?

**Comment by lewster32** [comment]
Closing due to no further information. Will re-open if an example is given.
