### ISSUE TITLE
Drag and drop seems to not be working

### ISSUE THREAD

**Issue by rndD** [lewster32/phaser-plugin-isometric#25]
Hi, first of all thank you for amazing plugin!

```
        var heroSprite = game.add.isoSprite(40, 40, 1, 'hero', 0);
        heroSprite.anchor.set(0.5, 0);

        heroSprite.inputEnabled = true;
        heroSprite.input.enableDrag();
```

But hero's sprite only blinking when I trying to drag it.
Can I use drag and drop feature from phaser?

**Comment by lewster32** [comment]
I don't think it'll work as expected (if at all) with enableDrag as enableDrag works in 2D screen space, whereas an IsoSprite expects to be positioned in 3D space. I think your best bet for implementing dragging is to look at [this example](http://www.rotates.org/phaser/iso/examples/interaction.htm) and add some functionality to check ```game.input.mousePointer.isDown```, track the currently selected tile and position it by doing ```heroSprite.isoPosition.copyFrom(cursorPos)``` or some equivalent. You'll have to ensure your z position makes sense in the context of your scene.

**Comment by wassname** [comment]
For anyone else attempting this, another approach is to use the drag events.
```javascript
updateDrag: function (sprite, pointer) {
    var newPos =  this.game.iso.unproject(pointer.position, undefined, sprite.isoZ);
    sprite.isoPosition.set(newPos.x,newPos.y,sprite.isoZ)
    // if we update isoPosition in update, the sprite flies off
    //this prevents that by update sprite.body.position and sprite.body.prev
    if (sprite.body.phase===2){
        sprite.body.preUpdate();
    }
}
```
