### ISSUE TITLE
how to draw staggered tilemaps?

### ISSUE THREAD

**Issue by soundyogi** [lewster32/phaser-plugin-isometric#28]
Hi!

I am trying without result to draw a tilemap

The projectionangle seems to play an important role (my tiles are 14h 16w)
more info on it would be nice and how to use it.

Is it possible to draw staggered maps?

thanks

**Comment by lewster32** [comment]
I think I'd need to see an example to be of more help. The projection angle defines the angle (in radians) between screen horizontal and the X or Y axis - there are some predefined ones, such as 'classic' (``Phaser.Plugin.Isometric.CLASSIC``) which is typically how 'isometric' pixel art is rendered at (26.565°) and true isometric (``Phaser.Plugin.Isometric.ISOMETRIC``) which is 30°. You can specify your own projection angles by working out the corresponding angle of your assets and converting it to radians.

**Comment by soundyogi** [comment]
Thank You very much.

Do I have to set the angle in radians or degrees in the engine?

I think my problems come from the fact that my tiles are 16x16 but I want the tilemap to be 14x16 for some overlap
(thats not possible and stupid I presume?)

That is the code to draw a staggered tilemap:

        
        function placeIsoStaggered(tile_index_x, tile_index_y){
            
            var local_x = tile_index_x * tile_width + tile_index_y % 2 * (tile_width/2)
            var local_y = -tile_index_y * (tile_height/2)

           //does not work 
           tile = game.add.isoSprite(local_x, local_y, 0, texture, 0, isoGroup)
           //works
           tile = game.add.sprite(local_x, local_y, texture, 0, isoGroup)

        }

**Comment by lewster32** [comment]
The projectionAngle is set in radians.

You can set your tiles to whatever size you want, you'll just have to ensure the projectionAngle matches their angle. The plug-in will attempt to create a bounding cube based on the size of the sprite you provide, which in most of my test cases acceptably bounded the sprite.

I can't be sure from your code, but is the problem that the tiles aren't in the correct order - i.e. they're overlapping incorrectly? If so, this is probably just a depth sorting issue, and you should be able to correct it using one of the sorting methods available - probably [simple sorting](http://udof.org/phaser/iso/doc/Phaser.Plugin.Isometric.Projector.html#simpleSort) if your tiles overlap. See [this example](http://www.rotates.org/phaser/iso/examples/realtime_depth_sorting.htm) for an implementation.

**Comment by soundyogi** [comment]
Hi, thanks for your patience.

1. Is there a way to use 16x16 sprites with a bounding box of 16x14 (ist this possible or will is just have to use sprites that fill the whole thing

atan(hight/width) is correct for radians yes?

2. Radians made it better but not quite - I pasted my staggered drawing code into on of your examples
(I dont get why the sprites are drawn strange .isoSprite() does call .sprite() anyway internally doesnt it?

The algorithm seems to work when calling normal .sprite()

![screen](https://cloud.githubusercontent.com/assets/3201046/11301609/c27a6ada-8f98-11e5-9fa8-c3e4de99eb43.png)


Thanks again!

**Comment by soundyogi** [comment]
You draw the diamond tilemap in 38px increments in this example - the sprite is 70x40px

Where do the 38px come from?
(is this my error?)

**Comment by soundyogi** [comment]
To calculate the angle I use atan(h/w) which "should" be correct. I will play around more the error has to be on my side somewhere.

In your examples the tiles are 70x40 but you place them in 38px increments, can you explain why?


Is it possible to adjust the bounding box of a tile?
I have 16x16 tiles but want some transparent overlap so the bounding box should be 14x16, is this possible?

**Comment by soundyogi** [comment]
Man I am terribly sorry to bother you but I just do not get it.

I cant even draw a goodlooking diamond map with my tiles (now 16x14 with a 16x14 sprite)
with your two for loops in the example (where do you get the 38px from?)

As for the staggered map:

    function placeIsoStaggered(tile_index_x, tile_index_y){
           
            var local_x = tile_index_x * tile_width + tile_index_y % 2 * (tile_width/2)
            var local_y = -tile_index_y * (tile_height/2)

            // does not work
            tile = game.add.isoSprite(local_x, local_y, 0, texture, 0, isoGroup)
            // works
            tile = game.add.sprite(local_x+100, local_y+100, texture, 0, isoGroup)
                
            tile.anchor.set(0.5, 0);
        }
        
        placeIsoStaggered(0,0)
        placeIsoStaggered(0,1)
        placeIsoStaggered(1,0)
        placeIsoStaggered(1,1)
        placeIsoStaggered(2,0)
        placeIsoStaggered(0,2)


![test](https://cloud.githubusercontent.com/assets/3201046/11325260/cd0ce3da-9149-11e5-87ed-292945a151e6.png)

**Comment by lewster32** [comment]
I'm not entirely sure but I think you may be trying to place the tiles isometrically, when the plug-in already takes care of this for you. On the screen, the x and y positions of Sprites will not be the same as the x and y positions of IsoSprites, as the plug-in does the isometric position for you.

**Comment by lewster32** [comment]
I've put together an example using your tile graphic - it seems like the projection angle and/or the spacing of your tiles was incorrect: http://jsfiddle.net/lewster32/bket612c/

**Comment by soundyogi** [comment]
Thank you so much! That helped.

**Comment by lewster32** [comment]
You're very welcome :) As this isn't an issue with the code itself, I'm marking it as closed, but it has allowed me to learn a little bit more about isometric maths, so thank you! :)
