### ISSUE TITLE
Cannot read property '4' of undefined

### ISSUE THREAD

**Issue by brenolf** [lewster32/phaser-plugin-isometric#30]
I'm running on this error that seems to be related that the file published both on bower and npm is not the same that we can find in the dist's master branch. The error is caused by a line testing `this.sprite._cache[4] === 1` in the minified version. If I copy the minified version from the master an paste it locally it works.

I believe you just need to republish the package.

**Comment by lewster32** [comment]
Unfortunately I'm not the maintainer of the library on npm - it was published by [Ilrein](https://www.npmjs.com/~ilrein), and clearly hasn't been kept up-to-date. The most current version will always be the master.
