### ISSUE TITLE
Adding Custom X/Y positions to adapt to the isometric grid

### ISSUE THREAD

**Issue by McFarts** [lewster32/phaser-plugin-isometric#32]
![](https://i.gyazo.com/08862afbadfff1d007a9c4b1e686dede.png)

So look here, I use my own map editor atm and their are 3 tiles on the screen with x/y positions

But, when I import using iso, they become like this:

![](https://i.gyazo.com/37ca296682f3fc684647c34587fcc33e.png)

I think it's because the isometric map is.. well, isometric and the x/y positions are not real positions. So is there some type of algorithm I can use to adjust the x, y positions? Thanks! They basically need to be flipped, right?

**Comment by wassname** [comment]
Flipping wont do it, you need to use unproject or look at the examples.  Did you check out the examples on the [website](http://rotates.org/phaser/iso/examples/)? They will get you started!

**Comment by McFarts** [comment]
ty will do, still learning the ropes here love this plugin
