### ISSUE TITLE
Does this plugin support isometric tilemaps?

### ISSUE THREAD

**Issue by gajuro** [lewster32/phaser-plugin-isometric#35]
I am not able to find this in the docs. Thank you.

**Comment by lewster32** [comment]
No, I'm afraid it doesn't support tilemaps out of the box - you'd have to implement them yourself. I don't think it'd be too much work to get an isometric map from tiled to render with this plug-in, however there'd probably be a lot more work optimising and supporting all of Tiled's features.

**Comment by gajuro** [comment]
I see. Thanks for the prompt answer anyway. 

God bless!
