### ISSUE TITLE
Static bodies

### ISSUE THREAD

**Issue by rafaelmembrives** [lewster32/phaser-plugin-isometric#36]
I want to create a player isoSprite that can jump over static isoSprites but the `body.static` property is undefined.

I have tried with `body.immovable=true` but this cause a strange behaviour. The player can´t push the blocks but when it jumps over one of thems it pull from it when increase o decrease the `body.velocity.y `. It´s very ease to replicate, take the "Basic character movement" example and add that after line 54:

`cube.body.immovable=true;`

Then jump over some cube and pres up or down cursor keys.

Thanks in advance

**Comment by wassname** [comment]
I can confirm this. I added the line, making the blocks immovable. Then I jumped on one and moved in the y direction (pressing up/down) which caused the block to move under me. No movement in the y direction.

**Comment by lewster32** [comment]
Well spotted - seems to have been a typo in the platform special case code in ```separateZ```.

**Comment by rafaelmembrives** [comment]
Now it works perfectly, thank you so much!

I´m using `body.immovable = true` and `body.allowGravity = false` to make static platforms like these ones in this 2D example:

http://phaser.io/examples/v2/p2-physics/static-body

I wonder if there´s a better way to do that...

**Comment by lewster32** [comment]
I think your way is the 'accepted' way to do it with Arcade/IsoArcade physics. I've created [examples](https://jsfiddle.net/lewster32/zxcqhfzq/) a while back for implementations in the standard 2D Arcade physics which <em>should</em> work basically the same in 3D IsoArcade. If you do spot any inconsistencies however, please do let me know and I'll see what I can do.
