### ISSUE TITLE
Jumping doesn't work when holding LEFT + UP

### ISSUE THREAD

**Issue by Frotty** [lewster32/phaser-plugin-isometric#37]
In this example: http://www.rotates.org/phaser/iso/examples/character.htm

When holding both arrowkeys and then trying to jump, it doesn't work. The other directions work though.

And now in my own game, I experience the same problem, that jumping doesn't work while walking in one specific direction.

How to fix this?

**Comment by lewster32** [comment]
This is a known issue and a limitation with certain keyboards called 'ghosting'. See the note at the top of this page: http://phaser.io/docs/2.4.4/Phaser.Keyboard.html and this page for an explanation of 'ghosting': https://www.microsoft.com/appliedsciences/antighostingexplained.mspx

**Comment by Frotty** [comment]
True, it works with my keyboard at home. Well this is garbitch

**Comment by lewster32** [comment]
I'd recommend trying different keys - cursors are notorious for this behaviour.

- Lewis Lane
www.rotates.org
