### ISSUE TITLE
isometric wall

### ISSUE THREAD

**Issue by AhmetOZALP** [lewster32/phaser-plugin-isometric#45]
-I added the picture library

-I added on top players

How do I do I do I want to come out of the water wall?

AND 

After a click you help I want to go to my place with this player mous

 

javascript file: https://jsfiddle.net/u61kub7b/

**Comment by orangeswim** [comment]
The tileset you provided in your example has expired.
You can have a waterfall sprite. Create a new group. Put your waterfall tiles into the new group and not into isoGroup.  Set `isoGroup.enableBody = true;`

I don't understand  your second question. I think my solution should do the walk through water wall trick.

**Comment by orangeswim** [comment]
Actually, here is working code.

[https://jsfiddle.net/td0fq53u/](https://jsfiddle.net/td0fq53u/)
You can paste it in [http://rotates.org/phaser/iso/examples/character.htm](http://rotates.org/phaser/iso/examples/character.htm) to test.

You can use processCallback in the collide function to cancel collisions between specific objects.
