### ISSUE TITLE
Box2d physic engine questions

### ISSUE THREAD

**Issue by Firanolfind** [lewster32/phaser-plugin-isometric#52]
Hi,
on which physic engine does this plugin based on? Is it compatible with [Box2d](https://phaser.io/shop/plugins/box2d)?
Thanks in advance for the answer.

**Comment by lewster32** [comment]
The physics engine in the plug-in is based on a (probably very outdated) version of Arcade (AABB) physics.

**Comment by Firanolfind** [comment]
Is it possible to integrate Box2d?

**Comment by lewster32** [comment]
Not easily, since the physics for isometric scenes is typically 3D, and the collisions involved are usually cuboid. I'd imagine you could do most of what you need with a less complicated physics engine, and if you do indeed need full 3D collision, you probably also need a full 3D renderer. What do you have in mind?

**Comment by Firanolfind** [comment]
Hi!
Actually I can't imagine why would I require 3D physic engine. In typical rpg games objects collide basically on 2d plane - "ground" so you can ignore z dimension. Does this plugin have some working examples, especially in 3D?
Previously I tried by my self to make own game with box2d. But of course, without quality game engine to finish it very difficult.
My thoughts was - Box2d allows to use complex fixtures and rich physic properties. On other side it just 2d. But in isometric rpg not often you can collide in **z**, and because it won't be complex collision we can approximate z collision as aabb or emulate it somehow.
If there will be implementation, would it be welcome to add such functionality to this plugin?
Thank you for response. I appreciate your patience in this conversation.

**Comment by lewster32** [comment]
I'm still struggling to think of a scenario where you'd require the complexity of Box2D physics in a '2.5D' isometric game? The Arcade physics engine built in to the plug-in offers AABB with fairly well optimised collision detection, separation and integration in 3 dimensions. By all means if you have a scenario in mind that absolutely requires something more than this, and can find a way to make it work well, then you'd be very welcome to contribute this to the plug-in and you'll be credited in full.

**Comment by Firanolfind** [comment]
Thank you for help!

**Comment by ggarek** [comment]
If i may to chime in, 

i think though the use cases of using box2d in 2.5D isomteric game may be not obvious, a few pop up in my mind. I think, that idea of using box2D fixtures in an isometric game is very exciting. We could use two objects connected with a spring with one moving by user controls and the other following driven by the fixture. Or we can build a physic-powered windmill and whatnot!
Of course, using 2d physics engine means that one have to isolate objects interactions in 2d space. But i think it still could be approached in this way and yield pretty interesting results.

Considering all of this, using full 3d physics engine for simulation may be a more correct option to choose (as @lewster32 mentioned), but i think the attempt of integrating box2d is at least worth trying.

I love 2.5D rendering and i always dreamed about making it feel more 3d-ish in terms of object interactions without violating the beauty of 2.5D art.

So imo it is definitely interesting experiment worth trying and sharing progress/results in some way.
